targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options for json_serializable
          include_if_null: false
          explicit_to_json: true
          field_rename: snake
      riverpod_generator:
        options:
          # Options for riverpod_generator
          provider_name_suffix: "Provider"
          keep_private_name: false
          enable_doc_comments: true
      freezed:
        options:
          # Options for freezed
          copy_with: true
          equal: true
          to_string: true
          union_key: "type"
          union_value_case: "snake"
