name: repeatwise_ui
description: A Flutter UI application for RepeatWise learning platform.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17

  # Navigation
  go_router: ^16.1.0

  # HTTP Client
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1

  # Local Storage
  shared_preferences: ^2.2.2

  # JSON Serialization
  json_annotation: ^4.9.0

  # Code Generation
  freezed_annotation: ^3.1.0

  # UI Components
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^3.0.0-dev.17
  json_serializable: ^6.7.1
  freezed: ^3.2.0

  # Linting
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/
  #   - icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
