global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot Backend
  - job_name: 'repeatwise-backend'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - repeatwise
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: repeatwise-backend
        action: keep
      - source_labels: [__meta_kubernetes_pod_container_port_number]
        regex: 8080
        action: keep
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_pod_container_name]
        target_label: container
      - source_labels: [__meta_kubernetes_pod_ip]
        target_label: __address__
        regex: (.+)
        replacement: ${1}:8080
    metrics_path: /actuator/prometheus

  # Flutter Frontend
  - job_name: 'repeatwise-frontend'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - repeatwise
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: repeatwise-frontend
        action: keep
      - source_labels: [__meta_kubernetes_pod_container_port_number]
        regex: 80
        action: keep
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_pod_container_name]
        target_label: container
      - source_labels: [__meta_kubernetes_pod_ip]
        target_label: __address__
        regex: (.+)
        replacement: ${1}:80
    metrics_path: /metrics

  # PostgreSQL Database
  - job_name: 'repeatwise-postgres'
    static_configs:
      - targets: ['repeatwise-postgres:5432']
    metrics_path: /metrics
    scrape_interval: 30s

  # Redis Cache
  - job_name: 'repeatwise-redis'
    static_configs:
      - targets: ['repeatwise-redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s

  # Node Exporter (if available)
  - job_name: 'node-exporter'
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - source_labels: [__meta_kubernetes_node_name]
        target_label: node
      - source_labels: [__meta_kubernetes_node_ip]
        target_label: __address__
        regex: (.+)
        replacement: ${1}:9100
