apiVersion: apps/v1
kind: Deployment
metadata:
  name: repeatwise-frontend
  namespace: repeatwise
  labels:
    app: repeatwise-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: repeatwise-frontend
  template:
    metadata:
      labels:
        app: repeatwise-frontend
    spec:
      containers:
      - name: frontend
        image: repeatwise-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: API_BASE_URL
          value: "http://repeatwise-backend:8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: repeatwise-frontend
  namespace: repeatwise
spec:
  selector:
    app: repeatwise-frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: repeatwise-frontend-hpa
  namespace: repeatwise
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: repeatwise-frontend
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
